# Import Library

In [1]:
import numpy as np
import pandas as pd
import json
import pickle
import jsonpickle
from io import StringIO
import matplotlib.pyplot as plt
from datamodel import OrderDepth, UserId, TradingState, Order, Trade, Observation
from typing import List
import string

# Import Data

In [1]:
a={1:1,2:2}

In [3]:
min(a.values())

1

In [2]:
def create_symbol_dfs(dataframe, symbols, col_name):
    # 创建一个空的列表来存储每个symbol的DataFrame
    dfs = []

    # 遍历给定的symbols列表
    for symbol in symbols:
        # 从原始DataFrame中筛选出对应于当前symbol的行
        filtered_df = dataframe[dataframe[col_name] == symbol]

        # 将筛选后的DataFrame添加到列表中
        dfs.append(filtered_df)

    # 返回包含每个symbol DataFrame的列表
    return dfs

In [3]:
trade_data_00 = pd.read_csv('trades_round_1_day_-2_nn.csv', delimiter=';')
trade_data_01 = pd.read_csv('trades_round_1_day_-1_nn.csv', delimiter=';')
trade_data_02 = pd.read_csv('trades_round_1_day_0_nn.csv', delimiter=';')

order_data_00 = pd.read_csv('prices_round_1_day_-2.csv', delimiter=';')
order_data_01 = pd.read_csv('prices_round_1_day_-1.csv', delimiter=';')
order_data_02 = pd.read_csv('prices_round_1_day_0.csv', delimiter=';')

In [4]:
trade_df_list = [trade_data_00, trade_data_01, trade_data_02]
symbols = ['STARFRUIT', 'AMETHYSTS']
trade_df = pd.DataFrame()

# 遍历df_list中的每个DataFrame
for df in trade_df_list:
    # 使用create_symbol_dfs函数为'STARFRUIT'和'AMETHYSTS'筛选数据
    symbol_dfs = create_symbol_dfs(df, symbols, 'symbol')
    # symbol_dfs[0]将是STARFRUIT的DataFrame，因为它是symbols列表中的第一个元素
    trade_df = pd.concat([trade_df, symbol_dfs[0]], ignore_index=True)

order_df_list = [order_data_00, order_data_01, order_data_02]
symbols = ['STARFRUIT', 'AMETHYSTS']
order_df = pd.DataFrame()

# 遍历df_list中的每个DataFrame
for df in order_df_list:
    # 使用create_symbol_dfs函数为'STARFRUIT'和'AMETHYSTS'筛选数据
    symbol_dfs = create_symbol_dfs(df, symbols, 'product')
    # symbol_dfs[0]将是STARFRUIT的DataFrame，因为它是symbols列表中的第一个元素
    order_df = pd.concat([order_df, symbol_dfs[0]], ignore_index=True)

In [5]:
trade_df

timestamp  buyer  seller     symbol   currency   price  quantity
0             0    NaN     NaN  STARFRUIT  SEASHELLS  5003.0         1
1           100    NaN     NaN  STARFRUIT  SEASHELLS  5004.0         6
2           900    NaN     NaN  STARFRUIT  SEASHELLS  5001.0         2
3          1000    NaN     NaN  STARFRUIT  SEASHELLS  4997.0         2
4          1100    NaN     NaN  STARFRUIT  SEASHELLS  4997.0         1
...         ...    ...     ...        ...        ...     ...       ...
8910     998500    NaN     NaN  STARFRUIT  SEASHELLS  5050.0         3
8911     998700    NaN     NaN  STARFRUIT  SEASHELLS  5055.0         1
8912     998800    NaN     NaN  STARFRUIT  SEASHELLS  5050.0         1
8913     999500    NaN     NaN  STARFRUIT  SEASHELLS  5049.0         2
8914     999600    NaN     NaN  STARFRUIT  SEASHELLS  5048.0         1

[8915 rows x 7 columns]

In [5]:
order_df

day  timestamp    product  bid_price_1  bid_volume_1  bid_price_2  \
0       -2          0  STARFRUIT         4997            26          NaN   
1       -2        100  STARFRUIT         5000             5       4998.0   
2       -2        200  STARFRUIT         4997             1       4996.0   
3       -2        300  STARFRUIT         4996            27          NaN   
4       -2        400  STARFRUIT         4995            20          NaN   
...    ...        ...        ...          ...           ...          ...   
29995    0     999500  STARFRUIT         5049            28          NaN   
29996    0     999600  STARFRUIT         5048             9       5047.0   
29997    0     999700  STARFRUIT         5053             1       5048.0   
29998    0     999800  STARFRUIT         5047            27          NaN   
29999    0     999900  STARFRUIT         5048             2       5047.0   

       bid_volume_2  bid_price_3  bid_volume_3  ask_price_1  ask_volume_1  \
0               NaN          NaN           NaN         5003            26   
1               6.0       4997.0          20.0         5004            20   
2              30.0          NaN           NaN         5003            31   
3               NaN          NaN           NaN         5003            27   
4               NaN          NaN           NaN         5002            20   
...             ...          ...           ...          ...           ...   
29995           NaN          NaN           NaN         5056            28   
29996          27.0          NaN           NaN         5054            29   
29997          26.0          NaN           NaN         5054             2   
29998           NaN          NaN           NaN         5052             1   
29999          21.0          NaN           NaN         5054            23   

       ask_price_2  ask_volume_2  ask_price_3  ask_volume_3  mid_price  \
0              NaN           NaN          NaN           NaN     5000.0   
1              NaN           NaN          NaN           NaN     5002.0   
2              NaN           NaN          NaN           NaN     5000.0   
3              NaN           NaN          NaN           NaN     4999.5   
4              NaN           NaN          NaN           NaN     4998.5   
...            ...           ...          ...           ...        ...   
29995          NaN           NaN          NaN           NaN     5052.5   
29996          NaN           NaN          NaN           NaN     5051.0   
29997       5055.0          24.0          NaN           NaN     5053.5   
29998       5054.0          27.0          NaN           NaN     5049.5   
29999          NaN           NaN          NaN           NaN     5051.0   

       profit_and_loss  
0                  0.0  
1                  0.0  
2                  0.0  
3                  0.0  
4                  0.0  
...                ...  
29995              0.0  
29996              0.0  
29997              0.0  
29998              0.0  
29999              0.0  

[30000 rows x 17 columns]

# Data Preprocessing

In [12]:
order_df['mid_price_diff'][9]

0.0

#### Feature: mid price change

In [127]:
# Calculate the mid price difference feature
order_df['mid_price_diff'] = order_df['mid_price'].diff()

# 步骤2: 构造特征和目标值
# 初始化特征和目标值的列表
features = []
targets = []

# 遍历DataFrame，为每个时间点构造特征和目标值
# Start from day 2, since the first day difference is 0
for i in range(8, len(order_df) - 1):
    # 当前及过去 N 个时间步的 mid price diff 作为特征
    feature = order_df['mid_price_diff'][i-7:i+1].values
    # price change direction as the target
    price_change_direction = np.sign(order_df['mid_price_diff'][i+1])
    features.append(feature)
    targets.append(price_change_direction)

# 步骤3: 创建新的DataFrame
model_df = pd.DataFrame(features, columns=['avg_price_diff_t-7', 'avg_price_diff_t-6', 'avg_price_diff_t-5', 'avg_price_diff-4',
                                           'avg_price_diff_t-3', 'avg_price_diff_t-2', 'avg_price_diff_t-1', 'avg_price_diff_t'])
model_df['target'] = targets

#### feature: s1_imbalance

In [128]:
order_df["s1_imbalance"] = (order_df["bid_volume_1"] - order_df["ask_volume_1"]) / (order_df["bid_volume_1"] + order_df["ask_volume_1"])
model_df["s1_imbalance"] = order_df["s1_imbalance"][8:-1].reset_index(drop=True)

In [129]:
# for target value that equals to 0, first make it into np.nan and ffill, then drop na
model_df['target'] = model_df['target'].replace(0, np.nan).ffill()
model_df = model_df.dropna()

In [111]:
a = (8,9)
print(type(a))
a[0]

<class 'tuple'>


8

In [130]:
model_df

avg_price_diff_t-7  avg_price_diff_t-6  avg_price_diff_t-5  \
1                    -2.0                -0.5                -1.0   
2                    -0.5                -1.0                 3.5   
3                    -1.0                 3.5                -2.5   
4                     3.5                -2.5                 0.5   
5                    -2.5                 0.5                 2.5   
...                   ...                 ...                 ...   
29986                -1.0                 1.0                -0.5   
29987                 1.0                -0.5                 0.0   
29988                -0.5                 0.0                -1.0   
29989                 0.0                -1.0                -0.5   
29990                -1.0                -0.5                 0.5   

       avg_price_diff-4  avg_price_diff_t-3  avg_price_diff_t-2  \
1                   3.5                -2.5                 0.5   
2                  -2.5                 0.5                 2.5   
3                   0.5                 2.5                 0.0   
4                   2.5                 0.0                -3.5   
5                   0.0                -3.5                 0.5   
...                 ...                 ...                 ...   
29986               0.0                -1.0                -0.5   
29987              -1.0                -0.5                 0.5   
29988              -0.5                 0.5                -0.5   
29989               0.5                -0.5                 1.0   
29990              -0.5                 1.0                -1.5   

       avg_price_diff_t-1  avg_price_diff_t  target  s1_imbalance  
1                     2.5               0.0    -1.0     -0.875000  
2                     0.0              -3.5     1.0     -0.600000  
3                    -3.5               0.5     1.0      0.785714  
4                     0.5               0.5     1.0      0.931034  
5                     0.5               2.0    -1.0     -0.769231  
...                   ...               ...     ...           ...  
29986                 0.5              -0.5     1.0      0.000000  
29987                -0.5               1.0    -1.0      0.000000  
29988                 1.0              -1.5     1.0     -0.526316  
29989                -1.5               2.5    -1.0     -0.333333  
29990                 2.5              -4.0     1.0      0.928571  

[29990 rows x 10 columns]

# Model Training

In [148]:
# fit a logistic regression model and store the class predictions using only s1_imbalance as the feature to predict the target
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Split the data into training and test sets
X = model_df['s1_imbalance'].values.reshape(-1, 1)
y = model_df['target'].values

# Fit a logistic regression model
model = LogisticRegression(solver='saga', class_weight='balanced')
model.fit(X, y)

y_pred_proba = model.predict_proba(X)
y_pred = np.where(y_pred_proba[:, 1] > 0.6, 1, -1)

# Calculate the accuracy of the model
accuracy = accuracy_score(y, y_pred)
print(f'Accuracy: {accuracy}')

Accuracy: 0.6243747915971991


In [150]:
z

array([[-0.97756779],
       [-0.66265941],
       [ 0.92415164],
       ...,
       [-0.57828204],
       [-0.35729371],
       [ 1.08774041]])

In [151]:
z = np.matmul(X, model.coef_.T) + model.intercept_
prob = 1/ (1+np.exp(-z))
y_pred_rep = np.where(prob > 0.6, 1, -1)

accuracy = accuracy_score(y, y_pred_rep)
print(f'Accuracy: {accuracy}')

Accuracy: 0.6243747915971991


In [147]:
print("Coefficients:", model.coef_)
print("Intercept:", model.intercept_)

Coefficients: [[1.14536629]]
Intercept: [0.02429364]


In [134]:
y_pred_proba

array([[0.72663427, 0.27336573],
       [0.65986414, 0.34013586],
       [0.28410281, 0.71589719],
       ...,
       [0.64067783, 0.35932217],
       [0.58838864, 0.41161136],
       [0.2520333 , 0.7479667 ]])

In [145]:
y_pred = np.where(y_pred_proba[:, 1] > 0.6, 1, -1)
y_pred

array([-1, -1,  1, ..., -1, -1,  1])

In [116]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Separate the features and target variable
X = model_df.drop("target", axis=1)
y = model_df["target"]

# Create and fit the logistic regression model
model = LogisticRegression(penalty='l1', solver='saga', class_weight='balanced', C=1, max_iter=1000)
model.fit(X, y)

# Make predictions on the test set
y_pred_proba = model.predict_proba(X)


In [117]:
y_pred_proba

array([[0.76235467, 0.23764533],
       [0.29201046, 0.70798954],
       [0.30299145, 0.69700855],
       ...,
       [0.36404645, 0.63595355],
       [0.68901754, 0.31098246],
       [0.22165587, 0.77834413]])

In [118]:
# when the probability of the positive class is greater than 0.7, return y_pred as 1, otherwise -1
y_pred = np.where(y_pred_proba[:, 1] > 0.7, 1, -1)

In [119]:
y_pred

array([-1,  1, -1, ..., -1, -1,  1])

In [120]:
# Evaluate the model's accuracy
accuracy = accuracy_score(y, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.5677559186395466


In [121]:
print("Coefficients:", model.coef_)
print("Intercept:", model.intercept_)

Coefficients: [[-0.02839707 -0.05048245 -0.10501895 -0.17026582 -0.26236442 -0.37601569
  -0.4910231  -0.52319539]]
Intercept: [0.00289805]


In [122]:
z = np.matmul(X, model.coef_.T) + model.intercept_
prob = 1/ (1+np.exp(-z.values))
y_pred_rep = np.where(prob > 0.7, 1, -1)

In [123]:
y_pred_rep

array([[-1],
       [ 1],
       [-1],
       ...,
       [-1],
       [-1],
       [ 1]])

In [124]:
y_pred_rep = y_pred_rep.reshape(-1,)
y_pred_rep

array([-1,  1, -1, ..., -1, -1,  1])

In [125]:
# check whether the y_pred_rep is the same as y_pred
np.array_equal(y_pred_rep, y_pred)

True

In [109]:
X

avg_price_diff_t-7  avg_price_diff_t-6  avg_price_diff_t-5  \
1                    -2.0                -0.5                -1.0   
2                    -0.5                -1.0                 3.5   
3                    -1.0                 3.5                -2.5   
4                     3.5                -2.5                 0.5   
5                    -2.5                 0.5                 2.5   
...                   ...                 ...                 ...   
29986                -1.0                 1.0                -0.5   
29987                 1.0                -0.5                 0.0   
29988                -0.5                 0.0                -1.0   
29989                 0.0                -1.0                -0.5   
29990                -1.0                -0.5                 0.5   

       avg_price_diff-4  avg_price_diff_t-3  avg_price_diff_t-2  \
1                   3.5                -2.5                 0.5   
2                  -2.5                 0.5                 2.5   
3                   0.5                 2.5                 0.0   
4                   2.5                 0.0                -3.5   
5                   0.0                -3.5                 0.5   
...                 ...                 ...                 ...   
29986               0.0                -1.0                -0.5   
29987              -1.0                -0.5                 0.5   
29988              -0.5                 0.5                -0.5   
29989               0.5                -0.5                 1.0   
29990              -0.5                 1.0                -1.5   

       avg_price_diff_t-1  avg_price_diff_t  s1_imbalance  
1                     2.5               0.0     -0.875000  
2                     0.0              -3.5     -0.600000  
3                    -3.5               0.5      0.785714  
4                     0.5               0.5      0.931034  
5                     0.5               2.0     -0.769231  
...                   ...               ...           ...  
29986                 0.5              -0.5      0.000000  
29987                -0.5               1.0      0.000000  
29988                 1.0              -1.5     -0.526316  
29989                -1.5               2.5     -0.333333  
29990                 2.5              -4.0      0.928571  

[29990 rows x 9 columns]

In [126]:
[1,2,3,4,5,6,7,8][-3:]

[6, 7, 8]