In [15]:
import numpy as np

base =7500
multiplier = np.array([[24,70,41,21,60],
                       [47,82,87,80,35],
                       [73,89,100,90,17],
                       [77,83,85,79,55],
                       [12,27,52,15,30]
                       ]).reshape(1,-1)
hunter = np.array([[2,4,3,2,4],
                    [3,5,5,5,3],
                    [4,5,8,7,2],
                    [5,5,5,5,4],
                    [2,3,4,2,3]
                    ]).reshape(1,-1)

In [ ]:
np.random.seed(0)

In [39]:
# generate a 20_000 x 25 matrix of random numbers
random_numbers = np.random.rand(20_000, 25)

In [40]:
random_numbers

array([[2.79650232e-01, 9.55731753e-01, 3.65958240e-02, ...,
        7.31310580e-01, 5.46736923e-01, 3.47383142e-01],
       [4.63458704e-01, 3.64767609e-01, 4.85158528e-01, ...,
        2.24275645e-01, 4.06108633e-01, 7.09615165e-01],
       [3.87786226e-02, 1.79829194e-01, 4.10723662e-01, ...,
        7.47917796e-01, 1.01493145e-01, 4.80019134e-02],
       ...,
       [6.44527213e-01, 3.35243674e-01, 5.01436489e-04, ...,
        9.19583123e-01, 5.54657044e-01, 4.85919923e-01],
       [3.67606578e-01, 8.49245939e-01, 8.52174735e-01, ...,
        8.32652428e-01, 7.14618142e-01, 4.22833807e-01],
       [2.25661171e-02, 3.65441967e-01, 9.17170702e-01, ...,
        3.64712711e-01, 8.01786538e-01, 6.92679666e-01]])

In [34]:
def profit_cal(random_numbers):
    random_numbers/=np.sum(random_numbers, axis=1)[:, None]
    random_numbers*=100
    #pnl
    pnl = np.mean(base*multiplier/(random_numbers+hunter), axis=0)
    return pnl

In [46]:
np.argsort(profit_cal(random_numbers))

array([20, 23, 14,  3, 21,  0, 24,  9,  2, 22, 19,  5,  4, 13, 12, 15, 18,
        8,  1,  6, 16, 10, 17,  7, 11], dtype=int64)

In [45]:
profit_cal(random_numbers)

array([36086.98759548, 72119.70831111, 49823.85335051, 31693.2120702 ,
       61796.43087672, 57181.57360284, 73280.97735822, 77704.4417103 ,
       71521.23502635, 42650.19309625, 74981.9760944 , 79865.40619988,
       64821.99919735, 64219.87156344, 25493.09197841, 68998.77132232,
       74325.7636934 , 76133.63204372, 70529.11359592, 56481.03878694,
       18101.84830581, 32918.73299417, 53489.91551373, 22587.48386857,
       36532.83973873])

In [38]:
# sanity check:

In [32]:
random_numbers[0][0]

4.424445753321162

In [33]:
base*24/(random_numbers[0][0]+hunter[0][0])

28017.981147548446