In [8]:
import numpy as np

base =7500
multiplier = np.array([[24,70,41,21,60],
                       [47,82,87,80,35],
                       [73,89,100,90,17],
                       [77,83,85,79,55],
                       [12,27,52,15,30]
                       ]).reshape(1,-1)
hunter = np.array([[2,4,3,2,4],
                    [3,5,5,5,3],
                    [4,5,8,7,2],
                    [5,5,5,5,4],
                    [2,3,4,2,3]
                    ]).reshape(1,-1)

In [9]:
np.random.seed(0)

In [10]:
# generate a 20_000 x 25 matrix of random numbers
random_numbers = np.random.rand(20_000, 25)

In [11]:
random_numbers

array([[0.5488135 , 0.71518937, 0.60276338, ..., 0.46147936, 0.78052918,
        0.11827443],
       [0.63992102, 0.14335329, 0.94466892, ..., 0.1289263 , 0.31542835,
        0.36371077],
       [0.57019677, 0.43860151, 0.98837384, ..., 0.97676109, 0.60484552,
        0.73926358],
       ...,
       [0.52177653, 0.7158295 , 0.98729077, ..., 0.16115189, 0.84855794,
        0.67855662],
       [0.99616519, 0.37231646, 0.55150441, ..., 0.05343017, 0.56335554,
        0.81760894],
       [0.73943784, 0.10190805, 0.38799923, ..., 0.53321674, 0.88081423,
        0.26561703]])

In [12]:
def profit_cal(random_numbers):
    random_numbers/=np.sum(random_numbers, axis=1)[:, None]
    random_numbers*=100
    #pnl
    pnl = np.mean(base*multiplier/(random_numbers+hunter), axis=0)
    return pnl

In [13]:
np.argsort(profit_cal(random_numbers))

array([20, 23, 14,  3, 21,  0, 24,  9,  2, 22, 19,  5,  4, 13, 12, 15, 18,
        8,  1,  6, 16, 10, 17,  7, 11], dtype=int64)

In [14]:
profit_cal(random_numbers)

array([35910.64054694, 72051.65766112, 49579.48744448, 31765.73656632,
       61585.15766461, 57084.21574458, 73426.72719085, 78061.4262666 ,
       71493.70712636, 42483.04238356, 75216.67097604, 79900.62368473,
       64930.60586799, 64175.7077176 , 25691.07080294, 68973.35774405,
       74246.14515434, 76010.60733642, 70836.51575147, 56383.73555082,
       18026.7792577 , 33008.48891748, 53476.49114524, 22604.59027799,
       36480.77016112])

In [19]:
uniform_pnl = profit_cal(random_numbers)

In [28]:
np.argsort(base*multiplier/(uniform_pnl/np.sum(uniform_pnl)*100+hunter))[0][::-1]

array([11,  7, 17, 16,  6, 12,  8, 18, 10, 13, 15,  1,  4, 19, 22,  5,  2,
        9, 24,  0, 21,  3, 14, 23, 20], dtype=int64)

In [29]:
multiplier

array([[ 24,  70,  41,  21,  60,  47,  82,  87,  80,  35,  73,  89, 100,
         90,  17,  77,  83,  85,  79,  55,  12,  27,  52,  15,  30]])

In [38]:
# sanity check:

In [32]:
random_numbers[0][0]

4.424445753321162

In [33]:
base*24/(random_numbers[0][0]+hunter[0][0])

28017.981147548446